### ISSUE TITLE
Merge branch BRM_Updates into master

### ISSUE THREAD

**Issue by rmscheller** [LANDIS-II-Foundation/Extension-Biomass-Insect#11]

**Comment by bmarron18** [comment]
After modification to the LandisData "InsectDefoliator" input .txt files (there were many additions and deletions of input variables after merging B. Miranda's changes), the QAQC test run stalled but likely not a major crash. Console output from the QAQC run is provided below:
....
Running NECN Succession ...
Current time: 3
Running Biomass Insects ...
   Processing landscape for Biomass Insect events ...
   Insect1 is active.  StartYear=3, StopYear=5, CurrentYear=3.
  Insect Start Time = 3, Stop Time = 5.
   Initializing Defoliation Patches...
Internal error occurred within the program:
  Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

Stack trace:
   at System.ThrowHelper.ThrowArgumentOutOfRangeException()
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Landis.Extension.Insects.Outbreak.InitializeDefoliationPatches(IInsect insect)
   at Landis.Extension.Insects.PlugIn.Run()
   at Landis.Model.Run(ExtensionMain extension)
   at Landis.Model.Run(String scenarioPath, IUserInterface ui)
   at Landis.App.Main(String[] args)

**Comment by bmarron18** [comment]
A set of code changes was made to fix the exceptions defined in my comment above. Unfortunately, the same major exception was thrown:

Loading Biomass Insects extension ...
   Begin parsing SPECIES table.
Internal error occurred within the program:
  Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

Stack trace:
   at System.ThrowHelper.ThrowArgumentOutOfRangeException()
   at System.Collections.Generic.List`1.set_Item(Int32 index, T value)
   at Landis.Extension.Insects.InsectParser.Parse()
   at Edu.Wisc.Forest.Flel.Util.TextParser`1.Parse(LineReader reader)
   at Landis.Data.Load[T](String path, ITextParser`1 parser)
   at Landis.Extension.Insects.InputParameterParser.Parse()
   at Edu.Wisc.Forest.Flel.Util.TextParser`1.Parse(LineReader reader)
   at Landis.Data.Load[T](String path, ITextParser`1 parser)
   at Landis.Extension.Insects.PlugIn.LoadParameters(String dataFile, ICore mCore)
   at Landis.Model.LoadExtensions(ExtensionAndInitFile[] extensions)
   at Landis.Model.Run(String scenarioPath, IUserInterface ui)
   at Landis.App.Main(String[] args)

**Comment by rmscheller** [comment]
Are there any new species in the insect input?

**Comment by bmarron18** [comment]
The QAQC example scenario still contains two spp ("defoliators") but the setup file changes to each spp (in "biomass-insects_InsectDefoliator1_s3e3" and biomass-insects_InsectDefoliator2_s3e3") required input variable changes  based on the revised InsectParser.cs. The variables for change were flagged by LANDISII during QAQC runs: 

Loading Biomass Insects extension ...
Error at line 9 of file "./biomass-insects_InsectDefoliator1_s3e3.txt":
  Found the name "MeanDuration" but expected one of these names:
    StartYear
    DurationDistribution

Loading Biomass Insects extension ...
Error at line 13 of file "./biomass-insects_InsectDefoliator1_s3e3.txt":
  Found the name "MaxDuration" but expected "DurationDistribution"


Loading Biomass Insects extension ...
Error at line 19 of file "./biomass-insects_InsectDefoliator1_s3e3.txt":
  Found the name "InitialPatchShapeCalibrator" but expected "InitialPatchOutbreakSensitivity"

**Comment by VSchuster** [comment]
There are multiple new inputVars for InsectDefoliator1 added. I can't find the source of these. Might be good to contact BRM to see what they do
Specifically in InsectParser:53-61
DurationDistribution
DurationParameter1
DurationParameter2
MaxDuration

There is also a inclusion of no longer existent ones in the InsectDefoliator1_s2e2.txt:
MeanDuration
StdDevDuration

These may relate to one of the parameters? I'm unsure what other effects this will have with the BRM updates

**Comment by rmscheller** [comment]
Brian,

Can you shed some light?  Thanks!

**Comment by bmarron18** [comment]
Attached is the scenario that was run for QAQC testing plus the fourth and fifth QAQC ProjectWorkLogs on the issue.
[QAQC_TestRun_BiomassInsects_Issue11_20170807.zip](https://github.com/LANDIS-II-Foundation/Extension-Biomass-Insects/files/1214788/QAQC_TestRun_BiomassInsects_Issue11_20170807.zip)

**Comment by brmiranda** [comment]
One issue with the example scenario is that the succession extension (regardless of which extension) must operate with a 1 year time step when running Biomass Insects.  This is defined in the Users Guide, but we have never identified a way for the insect extension to check what the succession time step is in order to validate it and throw a warning message if not 1 year.  Currently, the extension will run with the incorrect succession time step, but the insect behavior will not be correct.

The other issue I see, and likely the one causing the current crashes, is that all species need to be listed in the insect parameter file under SpeciesParameters.  There are 34 species listed in species_s3e3.txt, but only 10 species in biomass-insects_InsectDefoliator1_s3e3.txt and biomass-insects_InsectDefoliator2_s3e3.txt.  Species for which there should be no insect impact can be parameterized as:
sppname  3  0  1  0  1

At some point we had a SusceptibilityClass 4 to incorporate those species, but that change has gotten lost.  An improvement would be to reinstate that class 4 and treat any species not explicitly listed as being in class 4 and then mismatches in the species list would no longer be an issue.  Short-term solution would be to add a check on the species list and throw an error if not all species are listed.

**Comment by bmarron18** [comment]
Ah, good to know and thanks so much for the details. Will modify input files appropriately and re-run. Also, I'll add your suggested enhancements to our, this-would-be-great-to-do list.

**Comment by bmarron18** [comment]
Appropriate changes were made to the QAQC scenario test files (NECN-succession_SetUp_s3e3.txt, biomass-insects_InsectDefoliator1_s3e3.txt, biomass-insects_InsectDefoliator2_s3e3.txt) to reflect the comments above. The same exception was still thrown. 

[QAQC_TestRun_BiomassInsects_Issue11_20170811.zip](https://github.com/LANDIS-II-Foundation/Extension-Biomass-Insects/files/1218545/QAQC_TestRun_BiomassInsects_Issue11_20170811.zip)

**Comment by bmarron18** [comment]
A VS debugger evaluation of Biomass-Insects.csproj pointed to exceptions being thrown in both Outbreak.cs and in InsectParser.cs. VSchuster was able to repair the exception in Outbreak.cs and BMiranda successfully remedied the exception in InsectParser.cs.  The changes to the input files for Extension-Biomass-Insects will require revision to the QAQC_Examples in Support-Other (ie to
(1) BiomassSuccession_s2e2 and (2) NECN_s3e30 as well as to the example provided in the repository itself .

This issue can now be closed; QAQC files attached.

[QAQC_BiomassInsects_20170811.zip](https://github.com/LANDIS-II-Foundation/Extension-Biomass-Insects/files/1219358/QAQC_BiomassInsects_20170811.zip)
