### ISSUE TITLE
Remove Landis.Extension.Succession.Biomass.dll as a requisite build library

### ISSUE THREAD

**Issue by bmarron18** [LANDIS-II-Foundation/Extension-Biomass-Insect#6]
Extension-Biomass-Insect requires "Landis.Extension.Succession.Biomass.dll" to be in src\bin\Debug in order to build its own assembly. The library, "Landis.Extension.Succession.Biomass.dll" could be put into the Support-DLLs library, but a better option is to modify the src code of Extension-Biomass-Insect so as not to call this library in the .csproj file. Currently, at Line 70 in the .csproj file:

Reference Include="Landis.Extension.Succession.Biomass"

**Comment by rmscheller** [comment]
Bruce,
Indeed, if the dll isn't actually called, no need to include it.  If it is absolutely required, let's make a src\support-dlls\ sub-folder with a note that the dll is not coming from the central repository.

**Comment by VSchuster** [comment]
This can be closed
